In [1]:
import numpy as np
import statistics
import math


In [196]:
testInput = '''
5483143223
2745854711
5264556173
6141336146
6357385478
4167524645
2176841721
6882881134
4846848554
5283751526
After step 1:
6594254334
3856965822
6375667284
7252447257
7468496589
5278635756
3287952832
7993992245
5957959665
6394862637
After step 2:
8807476555
5089087054
8597889608
8485769600
8700908800
6600088989
6800005943
0000007456
9000000876
8700006848
After step 3:
0050900866
8500800575
9900000039
9700000041
9935080063
7712300000
7911250009
2211130000
0421125000
0021119000
After step 4:
2263031977
0923031697
0032221150
0041111163
0076191174
0053411122
0042361120
5532241122
1532247211
1132230211
After step 5:
4484144000
2044144000
2253333493
1152333274
1187303285
1164633233
1153472231
6643352233
2643358322
2243341322
After step 6:
5595255111
3155255222
3364444605
2263444496
2298414396
2275744344
2264583342
7754463344
3754469433
3354452433
After step 7:
6707366222
4377366333
4475555827
3496655709
3500625609
3509955566
3486694453
8865585555
4865580644
4465574644
After step 8:
7818477333
5488477444
5697666949
4608766830
4734946730
4740097688
6900007564
0000009666
8000004755
6800007755
After step 9:
9060000644
7800000976
6900000080
5840000082
5858000093
6962400000
8021250009
2221130009
9111128097
7911119976
After step 10:
0481112976
0031112009
0041112504
0081111406
0099111306
0093511233
0442361130
5532252350
0532250600
0032240000'''

In [197]:
inputText = '''5483143223
2745854711
5264556173
6141336146
6357385478
4167524645
2176841721
6882881134
4846848554
5283751526'''




In [198]:
tests = testInput.split(':')
testMaps = []
for test in tests:
    testMap = np.empty((rows, cols))
    testLines = test.split('\n')
    for row in range(rows):
        testValues = list(testLines[row+1])
        for col in range(cols):
            testMap[row][col] = int(testValues[col])
    testMaps.append(testMap)
print(testMaps) 

[array([[5., 4., 8., 3., 1., 4., 3., 2., 2., 3.],
       [2., 7., 4., 5., 8., 5., 4., 7., 1., 1.],
       [5., 2., 6., 4., 5., 5., 6., 1., 7., 3.],
       [6., 1., 4., 1., 3., 3., 6., 1., 4., 6.],
       [6., 3., 5., 7., 3., 8., 5., 4., 7., 8.],
       [4., 1., 6., 7., 5., 2., 4., 6., 4., 5.],
       [2., 1., 7., 6., 8., 4., 1., 7., 2., 1.],
       [6., 8., 8., 2., 8., 8., 1., 1., 3., 4.],
       [4., 8., 4., 6., 8., 4., 8., 5., 5., 4.],
       [5., 2., 8., 3., 7., 5., 1., 5., 2., 6.]]), array([[6., 5., 9., 4., 2., 5., 4., 3., 3., 4.],
       [3., 8., 5., 6., 9., 6., 5., 8., 2., 2.],
       [6., 3., 7., 5., 6., 6., 7., 2., 8., 4.],
       [7., 2., 5., 2., 4., 4., 7., 2., 5., 7.],
       [7., 4., 6., 8., 4., 9., 6., 5., 8., 9.],
       [5., 2., 7., 8., 6., 3., 5., 7., 5., 6.],
       [3., 2., 8., 7., 9., 5., 2., 8., 3., 2.],
       [7., 9., 9., 3., 9., 9., 2., 2., 4., 5.],
       [5., 9., 5., 7., 9., 5., 9., 6., 6., 5.],
       [6., 3., 9., 4., 8., 6., 2., 6., 3., 7.]]), array([[8., 8.,

In [199]:
def checkFlash(row, col):
    if col >= 0 and col < cols and row >= 0 and row < rows:
        octoMap[row][col] += 1
        flashOcto(row, col)

def flashOcto(row, col):
    currentValue = octoMap[row][col]
    
    if currentValue > 9 and currentValue < 150:
        octoMap[row][col] = 200
        checkFlash(row - 1, col - 1)
        checkFlash(row, col - 1)
        checkFlash(row + 1, col - 1)
        checkFlash(row - 1, col)
        checkFlash(row + 1, col)
        checkFlash(row - 1, col + 1)
        checkFlash(row, col + 1)
        checkFlash(row + 1, col + 1)
        
def checkEqual(octo, test):
    for row in range(rows):
        for col in range(cols):
            #
            if int(octo[row][col]) != int(test[row][col]):
                #print("nope")
                print(f"at {row},{col} {octo[row][col]} ? {test[row][col]}")
                return False
    return True

In [208]:
lines = inputText.split('\n')
rows = len(lines)
cols = (len(list(lines[0])))
    
octoMap = np.empty((rows, cols))
row = col = 0
for octoLine in lines:
    col = 0
    for octo in list(octoLine):
        octoMap[row][col] = int(octo)
        col += 1
    row += 1

print(octoMap) 

[[8. 5. 4. 8. 3. 3. 5. 6. 4. 4.]
 [6. 5. 7. 6. 5. 2. 1. 7. 8. 2.]
 [1. 2. 2. 3. 6. 7. 7. 7. 6. 2.]
 [1. 2. 8. 4. 7. 1. 3. 1. 1. 3.]
 [6. 1. 2. 5. 6. 5. 4. 7. 7. 8.]
 [6. 4. 3. 5. 7. 2. 6. 8. 4. 2.]
 [5. 6. 6. 4. 1. 7. 5. 5. 5. 6.]
 [1. 4. 4. 5. 7. 3. 6. 5. 5. 6.]
 [2. 2. 4. 8. 4. 7. 3. 5. 6. 8.]
 [6. 4. 5. 1. 4. 7. 3. 5. 2. 6.]]


In [209]:
print(octoMap)
previousFlashes = 0
flashes = 0
print(len(octoMap))
if not checkEqual(octoMap,testMaps[0]):
    print("nope")
#increment
for steps in range(1000):
    #print(steps)
    for row in range(rows):
        for col in range(cols):
            octoMap[row][col] += 1

    #flash
    for row in range(rows):
        for col in range(cols):
            flashOcto(row, col)

    #reset
    for row in range(rows):
        for col in range(cols):
            if octoMap[row][col] > 9:
                flashes += 1
                octoMap[row][col] = 0
    
    if flashes - previousFlashes == 100:
        print(f"allFlahsed step {steps + 1}")
    previousFlashes = flashes
                
    
#     if not checkEqual(octoMap,testMaps[steps+1]):
#         print("nope")
    #print(octoMap)
print(flashes)

[[8. 5. 4. 8. 3. 3. 5. 6. 4. 4.]
 [6. 5. 7. 6. 5. 2. 1. 7. 8. 2.]
 [1. 2. 2. 3. 6. 7. 7. 7. 6. 2.]
 [1. 2. 8. 4. 7. 1. 3. 1. 1. 3.]
 [6. 1. 2. 5. 6. 5. 4. 7. 7. 8.]
 [6. 4. 3. 5. 7. 2. 6. 8. 4. 2.]
 [5. 6. 6. 4. 1. 7. 5. 5. 5. 6.]
 [1. 4. 4. 5. 7. 3. 6. 5. 5. 6.]
 [2. 2. 4. 8. 4. 7. 3. 5. 6. 8.]
 [6. 4. 5. 1. 4. 7. 3. 5. 2. 6.]]
10
at 0,0 8.0 ? 5.0
nope
allFlahsed step 368
allFlahsed step 378
allFlahsed step 388
allFlahsed step 398
allFlahsed step 408
allFlahsed step 418
allFlahsed step 428
allFlahsed step 438
allFlahsed step 448
allFlahsed step 458
allFlahsed step 468
allFlahsed step 478
allFlahsed step 488
allFlahsed step 498
allFlahsed step 508
allFlahsed step 518
allFlahsed step 528
allFlahsed step 538
allFlahsed step 548
allFlahsed step 558
allFlahsed step 568
allFlahsed step 578
allFlahsed step 588
allFlahsed step 598
allFlahsed step 608
allFlahsed step 618
allFlahsed step 628
allFlahsed step 638
allFlahsed step 648
allFlahsed step 658
allFlahsed step 668
allFlahsed step 678
allF

In [195]:
print(flashes)

1601


In [207]:
inputText = '''8548335644
6576521782
1223677762
1284713113
6125654778
6435726842
5664175556
1445736556
2248473568
6451473526'''